import logoImage from '../images/logoImage.png'
import imageMe from '../images/imageMe.png'
import projet1 from '../images/projet1.png'
import projet2 from '../images/projet2.png'
import projet3 from '../images/projet3.png'
import projet4 from '../images/projet4.png'
import projet5 from '../images/projet5.png'
import projet6 from '../images/projet6.png'
import projet7 from '../images/projet7.png'
import projet8 from '../images/projet8.png'
import projet9 from '../images/projet9.png'
import projet10 from '../images/projet10.png'
import projet11 from '../images/projet11.png'
import projet12 from '../images/projet12.png'
export {logoImage, imageMe, projet1, projet2, projet3, projet4, projet5, projet6, projet7, projet8, projet9, projet10, projet11, projet12}